Briareos\ChatBundle\Entity\ChatConversation:
    type: entity
    table: chat__conversation
    repositoryClass: Briareos\ChatBundle\Entity\ChatConversationRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        lastMessageRead:
            type: integer
            nullable: false
            default: 0
        lastMessageCleared:
            type: integer
            nullable: false
            default: 0
    manyToOne:
        subject:
            targetEntity: ChatSubjectInterface
            joinColumn:
                name: subject_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
        partner:
            targetEntity: ChatSubjectInterface
            joinColumn:
                name: partner_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    lifecycleCallbacks: {  }
