Briareos\ChatBundle\Entity\ChatMessage:
    type: entity
    table: chat__message
    repositoryClass: Briareos\ChatBundle\Entity\ChatMessageRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        sender:
            targetEntity: ChatSubjectInterface
            joinColumn:
                name: sender_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
        receiver:
            targetEntity: ChatSubjectInterface
            joinColumn:
                name: receiver_id
                referencedColumnName: id
                nullable: false
                onDelete: CASCADE
    lifecycleCallbacks: {  }
