parameters:
    chat.subject_pre_remove_listener.class: Briareos\ChatBundle\Listener\ChatSubjectRemoveListener

services:
    user.listener:
        class: %chat.subject_pre_remove_listener.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }