services:
    chat_subject.listener:
        class: Briareos\ChatBundle\Listener\ChatSubjectRemoveListener
        tags:
            - { name: doctrine.event_listener, event: preRemove }
    chat_subject.picture_provider:
        class: Briareos\ChatBundle\Subject\PlaceholditPictureProvider
        arguments: [ 32x32 ]
    chat_subject.presence_provider:
        class: Briareos\ChatBundle\Subject\BasicPresenceProvider
        arguments: [ @doctrine.orm.default_entity_manager ]
