parameters:
    chat_subject.listener.class: Briareos\ChatBundle\Listener\ChatSubjectRemoveListener

services:
    chat_subject.listener:
        class: %chat_subject.listener.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }