<?php

namespace Briareos\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatConversationRepository extends EntityRepository
{
}