<?php

namespace Briareos\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * ChatMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatMessageRepository extends EntityRepository
{
    public function getSubjectMessages(ChatSubjectInterface $subject)
    {
        $connection = $this->getEntityManager()->getConnection();
        /** @var $result \Doctrine\DBAL\Driver\Statement */
        $result = $connection->executeQuery('SELECT message.id, state.subject_id AS partner_id, message.text, message.createdAt,
          (message.sender_id = state.subject_id) AS received,
          ((conversation.lastMessageRead < message.id) AND :subject_id != message.sender_id) AS new
          FROM chat__message message
          LEFT JOIN chat__state state ON IF(:subject_id = message.sender_id, state.subject_id = message.receiver_id, state.subject_id = message.sender_id)
          LEFT JOIN chat__conversation conversation ON conversation.subject_id = :subject_id AND conversation.partner_id = state.subject_id
          WHERE (message.id > conversation.lastMessageCleared)
            AND (message.receiver_id = :subject_id OR message.sender_id = :subject_id)
          ORDER BY message.id ASC', array(
            ':subject_id' => $subject->getId(),
        ));
        return $result->fetchAll(\PDO::FETCH_CLASS);
    }
}