<?php

namespace Briareos\ChatBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Briareos\ChatBundle\Entity\ChatSubjectInterface;
use Briareos\ChatBundle\Entity\ChatState;

/**
 * ChatStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatStateRepository extends EntityRepository
{
    public function getOpenStates(ChatSubjectInterface $subject)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->where('FindInSet(:subject_id, s.openConversations) > 0');
        $qb->setParameter(':subject_id', $subject->getId());
        return $qb->getQuery()->execute();
    }

    /**
     * @param ChatSubjectInterface $subject
     * @return ChatState
     */
    public function getChatState(ChatSubjectInterface $subject)
    {
        $chatState = $this->findOneBy(array(
            'subject' => $subject,
        ));
        if (null === $chatState) {
            $chatState = new ChatState($subject);
            /** @var $em \Doctrine\ORM\EntityManager */
            $em = $this->getEntityManager();
            $em->persist($chatState);
            $em->flush($chatState);
        }
        return $chatState;
    }
}